FROM ghcr.io/wiedehopf/readsb-builder:latest AS builder

SHELL ["/bin/bash", "-x", "-o", "pipefail", "-c"]
COPY . /app/git
RUN find /app/git -maxdepth 2 -name "*.o" -delete && rm -f /app/git/readsb /app/git/viewadsb /app/git/.version && \
    cd /app/git && \
    READSB_BUILD_DIR=$(mktemp -d) && \
    cp -aT /app/git $READSB_BUILD_DIR && \
    cd $READSB_BUILD_DIR && \
    [[ $(uname -m) == x86_64 ]] && MARCH=" -march=nehalem" || MARCH="" && \
    make -j$(nproc) RTLSDR=yes OPTIMIZE="-O2 $MARCH" && \
    mv readsb /usr/local/bin && \
    mv viewadsb /usr/local/bin && \
    chmod +x /usr/local/bin/viewadsb /usr/local/bin/readsb && \
    make clean && \
    make -j$(nproc) WITH_UUIDS=yes OPTIMIZE="-O2 $MARCH" && \
    mv readsb /usr/local/bin/readsb-with-uuids && \
    make clean && \
    make -j$(nproc) PRINT_UUIDS=yes TRACKS_UUID=yes OPTIMIZE="-O2 $MARCH" && \
    mv readsb /usr/local/bin/readsb-uuid && \
    mv viewadsb /usr/local/bin/viewadsb-uuid && \
    chmod +x /usr/local/bin/viewadsb-uuid && \
    chmod +x /usr/local/bin/readsb-uuid && \
    rm -rf $READSB_BUILD_DIR && \
    mkdir -p  /usr/local/share/tar1090 && \
    wget -q -O /usr/local/share/tar1090/aircraft.csv.gz https://github.com/wiedehopf/tar1090-db/raw/csv/aircraft.csv.gz || touch /usr/local/share/tar1090/aircraft.csv.gz && \
    true

FROM debian:bookworm-slim
COPY --from=builder /usr/local/bin/readsb* /usr/local/bin/
COPY --from=builder /usr/local/bin/viewadsb* /usr/local/bin/
COPY --from=builder /usr/local/lib/libjemalloc.so.2 /usr/local/lib/libjemalloc.so.2
RUN mkdir -p /usr/local/share/tar1090
COPY --from=builder /usr/local/share/tar1090/aircraft.csv.gz /usr/local/share/tar1090/
RUN \
    apt-get update && \
    apt-get -y install --no-install-recommends \
    librtlsdr0 libncurses6 zlib1g libzstd1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    mkdir -p /run/readsb && \
    true

ENV LD_PRELOAD=/usr/local/lib/libjemalloc.so.2
ENV MALLOC_CONF=narenas:1,tcache:false

ENTRYPOINT ["/usr/local/bin/readsb"]
